In [3]:
import numpy as np

# Creation of the numpy array

In [6]:
type(np.array([1,2,3]))

numpy.ndarray

In [10]:
# 2d array
td = np.array([[1,2,3],[1,2,3]])
td

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
# 3d 
thrd = np.array([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])
thrd  # also called as tensors

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [15]:
# dtype array
np.array([1,2,3],dtype='float32')
np.array([1,2,3],dtype='float32').dtype

dtype('float32')

In [16]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
# arange
np.arange(1,11,2)   # this is just like the range function

array([1, 3, 5, 7, 9])

In [20]:
# reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
np.arange(1,13).reshape(2,6) 
#this only happen when u fullfill the requirement that m*n is equal to the no. of column

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
#np.random 
np.random.random((3,4))

array([[0.54426694, 0.2336438 , 0.12507838, 0.60587458],
       [0.84887413, 0.05878721, 0.52850044, 0.62745618],
       [0.01599406, 0.77276802, 0.69350275, 0.58784676]])

In [32]:
# np.linspace 
np.linspace(-10,10,10).reshape(2,5)
# first and the second no. tells the range and the last no. tells us the no. of no.we want

# in this the points are generated at equal distance 

array([[-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
         -1.11111111],
       [  1.11111111,   3.33333333,   5.55555556,   7.77777778,
         10.        ]])

In [33]:
# np.identity 
# to create the identity matrix of the given shape
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Attributes of numpy array

In [34]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2) # isme pehla wala 2 batata he ki kitne 2d array he baki dono 2d ka shape

In [37]:
#ndim
a3.ndim

3

In [38]:
# shape
a3.shape

(2, 2, 2)

In [39]:
#size
a3.size

8

In [44]:
#item size
a3.itemsize # tells us how much space is required by the each item of the array

4

In [47]:
#dtype
a1.dtype

dtype('int32')

# Changing the datatype of the array

In [50]:
# astype
a1.astype(np.int32)
# we use this when we are working with the large datasets

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a1.dtype

dtype('int32')

# Array operations

In [52]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [58]:
# Scalar Operations or arithmatic 
a1**2,a1*2

(array([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]], dtype=int32),
 array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]]))

In [60]:
# relational operator
a1 >= 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [62]:
# vector operation arithmatic
a1 + a2, a1**a2

(array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]),
 array([[          0,           1,       16384,    14348907],
        [          0, -1564725563,  1159987200,   442181591],
        [          0,  1914644777, -1304428544,  -122979837]], dtype=int32))

# Array Function

In [63]:
a1 = np.random.random((3,3))
a2 = np.round(a1*100)

In [66]:
a2,a1

(array([[73., 14., 33.],
        [58., 61., 21.],
        [47., 77., 13.]]),
 array([[0.7289065 , 0.14242503, 0.32850475],
        [0.57657722, 0.6112909 , 0.21201569],
        [0.46858907, 0.76729669, 0.12617496]]))

In [72]:
# max / min / sum / prod
np.max(a1) , np.min(a1) , np.sum(a2) , np.prod(a2)

(0.767296692086683, 0.1261749615968769, 397.0, 117889165750356.0)

In [74]:
# if har row ka minimum chahiye tab
np.min(a2,axis=1) # axis agar 1 he toh rowise  or 0 he toh column wise

array([14., 21., 13.])

In [78]:
# mean / median / std / var
np.mean(a2) , np.median(a2) , np.std(a2) , np.var(a2)

(44.111111111111114, 47.0, 23.416254774287047, 548.320987654321)

In [80]:
np.mean(a2,axis=0) , np.median(a2,axis=1) , np.std(a2,axis=0) , np.var(a2,axis=1)

(array([59.33333333, 50.66666667, 22.33333333]),
 array([33., 58., 47.]),
 array([10.65624491, 26.73740617,  8.21921867]),
 array([604.66666667, 330.88888889, 683.55555556]))

In [81]:
# trignometric function
np.sin(a2)

array([[-0.67677196,  0.99060736,  0.99991186],
       [ 0.99287265, -0.96611777,  0.83665564],
       [ 0.12357312,  0.99952016,  0.42016704]])

In [83]:
# dot product 
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
np.dot(a1,a2)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [84]:
# log and exponent 
np.log(a1) , np.exp(a1)

C:\Users\mynam\AppData\Local\Temp/ipykernel_12064/3293755341.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a1) , np.exp(a1)


(array([[      -inf, 0.        , 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947, 1.94591015],
        [2.07944154, 2.19722458, 2.30258509, 2.39789527]]),
 array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
        [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]]))

In [92]:
# round / ceil / floor
a1 = np.random.random((2,3))*100 
print(a1)
print()
print(np.round(a1))# inorder to get integers we use round
print()
print(np.floor(a1)) # to get the floor value
print()
print(np.ceil(a1))

[[63.44221052 87.52372018 89.76619469]
 [ 6.3222066  61.4162711  70.49801125]]

[[63. 88. 90.]
 [ 6. 61. 70.]]

[[63. 87. 89.]
 [ 6. 61. 70.]]

[[64. 88. 90.]
 [ 7. 62. 71.]]


# Indexing and Slicing

In [93]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [96]:
a1[-1], a1[0], a1[3]

(9, 0, 3)

In [98]:
print(a2)
a2[2][3]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


11.0

In [102]:
print(a3)
a3[1,0,1] , a3[0,0,0]
# pehle batana he ki konsa wala 2d array me he aur fir konsa row me he for konsa column me he
# same thing can be implemented in the 4 array and ndarray first we ask konsa wale (n-1)d array me he aur 
# jab tak 2 nahi ho raha tabtak puchenge aur 2d array hote he row and column wise nikalenge 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


(5, 0)

In [104]:
# slicing 
a1[2:6:2]

array([2, 4])

In [110]:
print(a2)
a2[0:2,:] , a2[:,3]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


(array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([ 3.,  7., 11.]))

In [111]:
a2[1:,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [117]:
a2[::2,::3]  ,  a2[::2,1::2]

(array([[ 0.,  3.],
        [ 8., 11.]]),
 array([[ 1.,  3.],
        [ 9., 11.]]))

In [128]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)
a3[::2,:,:] , a3[0,1,] , a3[1,:,1] , a3[2,1:,1:] ,  a3[::2,0,::2]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


(array([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],
 
        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]]),
 array([3, 4, 5]),
 array([10, 13, 16]),
 array([[22, 23],
        [25, 26]]),
 array([[ 0,  2],
        [18, 20]]))

# Iterating

In [130]:
print(a1)
for i in a1:
    print(i,end=" ")

[0 1 2 3 4 5 6 7 8 9]
0 1 2 3 4 5 6 7 8 9 

In [132]:
print(a2)
for i in a2: # har baar ek row
    for j in i: # fir uske andar ka values
        print(j,end="  ")

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  10.0  11.0  

In [133]:
print(a3)
for i in a3:
    for j in i:
        for k in j:
            print(k,end= "  ")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  

In [135]:
# np.nditer
for i in np.nditer(a3):
    print(i,end="  ")

0  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  

# Reshaping

In [137]:
# transpose
a2.T  # ya np.transpose()

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [138]:
# Ravel
a3.ravel() # kitne bhi dimension ka matrice ko 1d me change kardeta h e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking 

In [139]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [140]:
# horizontal stacking  (jodna 2 ya 2 se zayada np.array ko)
np.hstack((a1,a2)) , np.hstack((a2,a1))

TypeError: _vhstack_dispatcher() takes 1 positional argument but 2 were given