In [1]:
import numpy as np

# np.sort
* Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([92, 84, 39,  4, 94, 51, 62, 93, 91,  5, 80, 17, 45, 30, 23])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[34, 12, 12, 14],
       [49, 55, 84, 80],
       [24, 47, 25, 22],
       [98, 19, 87, 76],
       [57, 36, 60, 66],
       [65, 83, 22, 39]])

In [4]:
np.sort(a)[::-1]

array([94, 93, 92, 91, 84, 80, 62, 51, 45, 39, 30, 23, 17,  5,  4])

In [5]:
np.sort(b,axis=0)

array([[24, 12, 12, 14],
       [34, 19, 22, 22],
       [49, 36, 25, 39],
       [57, 47, 60, 66],
       [65, 55, 84, 76],
       [98, 83, 87, 80]])

# np.append
* The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# code
np.append(a,200)

array([ 92,  84,  39,   4,  94,  51,  62,  93,  91,   5,  80,  17,  45,
        30,  23, 200])

In [7]:
b

array([[34, 12, 12, 14],
       [49, 55, 84, 80],
       [24, 47, 25, 22],
       [98, 19, 87, 76],
       [57, 36, 60, 66],
       [65, 83, 22, 39]])

In [8]:
np.append(b,np.random.random((b.shape[0],1)),axis=1) # ye column wise he but axis rows ko match karna chahiye 

array([[34.        , 12.        , 12.        , 14.        ,  0.15291189],
       [49.        , 55.        , 84.        , 80.        ,  0.53204302],
       [24.        , 47.        , 25.        , 22.        ,  0.3529014 ],
       [98.        , 19.        , 87.        , 76.        ,  0.4338198 ],
       [57.        , 36.        , 60.        , 66.        ,  0.90372434],
       [65.        , 83.        , 22.        , 39.        ,  0.69394617]])

In [10]:
np.append(b,np.random.random((2,b.shape[1])),axis=0) 
# ye row wise addition he but axis column ko match karna chahiye

array([[3.40000000e+01, 1.20000000e+01, 1.20000000e+01, 1.40000000e+01],
       [4.90000000e+01, 5.50000000e+01, 8.40000000e+01, 8.00000000e+01],
       [2.40000000e+01, 4.70000000e+01, 2.50000000e+01, 2.20000000e+01],
       [9.80000000e+01, 1.90000000e+01, 8.70000000e+01, 7.60000000e+01],
       [5.70000000e+01, 3.60000000e+01, 6.00000000e+01, 6.60000000e+01],
       [6.50000000e+01, 8.30000000e+01, 2.20000000e+01, 3.90000000e+01],
       [6.77947867e-01, 7.87505379e-01, 9.13865497e-01, 2.30291762e-01],
       [3.46106804e-01, 5.10818406e-01, 2.72660262e-01, 5.77591231e-03]])

# np.concatenate
* numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [16]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
a = np.arange(3).reshape(1,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
np.concatenate((c,a),axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2]])

In [18]:
np.concatenate((c,a),axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [13]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique
* With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [14]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [15]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims
* With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [21]:
# code
a.shape

(1, 3)

In [22]:
np.expand_dims(a,axis=0).shape

(1, 1, 3)

In [97]:
np.expand_dims(a,axis=1).shape

(15, 1)

# np.where
The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [36]:
a = np.random.randint(1,25,15)

In [41]:
a

array([18, 12,  1, 22,  9,  5, 16, 19, 21, 19, 23, 10,  8, 15,  5])

In [ ]:
# np.where(condition,(if condition is true),(if condition is false))

In [38]:
# find all indices with value greater than 50
np.where(a>20)

(array([ 3,  8, 10], dtype=int64),)

In [39]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([18, 12,  1, 22,  9,  5, 16, 19, 21, 19, 23, 10,  8, 15,  5])

In [43]:
np.where(a%3 == 0,0,a)

array([ 0,  0,  1, 22,  0,  5, 16, 19,  0, 19, 23, 10,  8,  0,  5])

# np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [46]:
# code
a

array([18, 12,  1, 22,  9,  5, 16, 19, 21, 19, 23, 10,  8, 15,  5])

In [48]:
np.argmax(a) , a[10]

(10, 23)

In [49]:
b

array([[34, 12, 12, 14],
       [49, 55, 84, 80],
       [24, 47, 25, 22],
       [98, 19, 87, 76],
       [57, 36, 60, 66],
       [65, 83, 22, 39]])

In [51]:
np.argmax(b,axis=0) # column wise sabse bada element ka index batata h

array([3, 5, 3, 1], dtype=int64)

In [52]:
np.argmax(b,axis=1)

array([0, 2, 1, 0, 3, 1], dtype=int64)

In [53]:
# np.argmin
np.argmin(a)

2

# np.cumsum
numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [54]:
a

array([18, 12,  1, 22,  9,  5, 16, 19, 21, 19, 23, 10,  8, 15,  5])

In [55]:
np.cumsum(a)

array([ 18,  30,  31,  53,  62,  67,  83, 102, 123, 142, 165, 175, 183,
       198, 203], dtype=int32)

In [56]:
b

array([[34, 12, 12, 14],
       [49, 55, 84, 80],
       [24, 47, 25, 22],
       [98, 19, 87, 76],
       [57, 36, 60, 66],
       [65, 83, 22, 39]])

In [57]:
np.cumsum(b,axis=1)

array([[ 34,  46,  58,  72],
       [ 49, 104, 188, 268],
       [ 24,  71,  96, 118],
       [ 98, 117, 204, 280],
       [ 57,  93, 153, 219],
       [ 65, 148, 170, 209]], dtype=int32)

In [58]:
np.cumsum(b,axis=0)

array([[ 34,  12,  12,  14],
       [ 83,  67,  96,  94],
       [107, 114, 121, 116],
       [205, 133, 208, 192],
       [262, 169, 268, 258],
       [327, 252, 290, 297]], dtype=int32)

In [59]:
np.cumsum(b)

array([  34,   46,   58,   72,  121,  176,  260,  340,  364,  411,  436,
        458,  556,  575,  662,  738,  795,  831,  891,  957, 1022, 1105,
       1127, 1166], dtype=int32)

In [60]:
# np.cumprod
np.cumprod(a)

array([        18,        216,        216,       4752,      42768,
           213840,    3421440,   65007360, 1365154560,  168132864,
       -427911424,   15853056,  126824448, 1902366720,  921899008],
      dtype=int32)

In [61]:
a

array([18, 12,  1, 22,  9,  5, 16, 19, 21, 19, 23, 10,  8, 15,  5])

# np.percentile
numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [62]:
a

array([18, 12,  1, 22,  9,  5, 16, 19, 21, 19, 23, 10,  8, 15,  5])

In [63]:
np.percentile(a,50)

15.0

In [64]:
np.median(a)

15.0

# np.histogram
Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [65]:
a

array([18, 12,  1, 22,  9,  5, 16, 19, 21, 19, 23, 10,  8, 15,  5])

In [66]:
np.histogram(a,bins=[0,50,100])

(array([15,  0], dtype=int64), array([  0,  50, 100]))

# np.corrcoef
Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [74]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,5,1.5,1.5,4])

np.corrcoef(salary,experience)

array([[1.       , 0.7387987],
       [0.7387987, 1.       ]])

# np.isin
With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [68]:
a

array([18, 12,  1, 22,  9,  5, 16, 19, 21, 19, 23, 10,  8, 15,  5])

In [69]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([10])

# np.flip
The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [75]:
a

array([18, 12,  1, 22,  9,  5, 16, 19, 21, 19, 23, 10,  8, 15,  5])

In [76]:
np.flip(a)

array([ 5, 15,  8, 10, 23, 19, 21, 19, 16,  5,  9, 22,  1, 12, 18])

In [77]:
b

array([[34, 12, 12, 14],
       [49, 55, 84, 80],
       [24, 47, 25, 22],
       [98, 19, 87, 76],
       [57, 36, 60, 66],
       [65, 83, 22, 39]])

In [78]:
np.flip(b,axis=1)

array([[14, 12, 12, 34],
       [80, 84, 55, 49],
       [22, 25, 47, 24],
       [76, 87, 19, 98],
       [66, 60, 36, 57],
       [39, 22, 83, 65]])

# np.put
The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [81]:
a

array([110, 530,   1,  22,   9,   5,  16,  19,  21,  19,  23,  10,   8,
        15,   5])

In [80]:
np.put(a,[0,1],[110,530])  
# np.put(array,(indixes where u want to change),(with what u want to change))
# the changes takes in the original array

In [82]:
a

array([110, 530,   1,  22,   9,   5,  16,  19,  21,  19,  23,  10,   8,
        15,   5])

# np.delete
The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [84]:
np.delete(a,[0,2,4])  # delete the values of the given index

array([530,  22,   5,  16,  19,  21,  19,  23,  10,   8,  15,   5])

# Set functions
* np.union1d
* np.intersect1d
* np.setdiff1d
* np.setxor1d
* np.in1d

In [85]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])
# returns the union of the 1d array
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [86]:
np.intersect1d(m,n)
# return the intersection point for the 1d array

array([3, 4, 5])

In [87]:
np.setdiff1d(n,m) #(ho,na ho)
# return the difference in both the 1d array set
# matlab n me ho aur m me na ho

array([6, 7])

In [88]:
np.setxor1d(m,n)# dono me common ko hatadega aur different ko rakhlega

array([1, 2, 6, 7])

In [90]:
m[np.in1d(m,1)] 
np.in1d(m,1) 

# checks if there is the element given as argument in 1d

array([ True, False, False, False, False])

# np.clip
numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [91]:
a

array([110, 530,   1,  22,   9,   5,  16,  19,  21,  19,  23,  10,   8,
        15,   5])

In [93]:
np.clip(a,a_min=20,a_max=75) # matlab sari values ab 20 aur 75 ke beech me hi rahegi

array([75, 75, 20, 22, 20, 20, 20, 20, 21, 20, 23, 20, 20, 20, 20])

# 17. np.swapaxes
Interchange two axes of an array.
https://numpy.org/doc/1.17/reference/generated/numpy.swapaxes.html

In [96]:
# basicaly it swap two axes of an array
a, a.shape

(array([110, 530,   1,  22,   9,   5,  16,  19,  21,  19,  23,  10,   8,
         15,   5]),
 (15,))

In [102]:
np.expand_dims(a,axis=0).shape

(1, 15)