In [1]:
import numpy as np

# np.sort
* Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([92, 84, 39,  4, 94, 51, 62, 93, 91,  5, 80, 17, 45, 30, 23])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[34, 12, 12, 14],
       [49, 55, 84, 80],
       [24, 47, 25, 22],
       [98, 19, 87, 76],
       [57, 36, 60, 66],
       [65, 83, 22, 39]])

In [4]:
np.sort(a)[::-1]

array([94, 93, 92, 91, 84, 80, 62, 51, 45, 39, 30, 23, 17,  5,  4])

In [5]:
np.sort(b,axis=0)

array([[24, 12, 12, 14],
       [34, 19, 22, 22],
       [49, 36, 25, 39],
       [57, 47, 60, 66],
       [65, 55, 84, 76],
       [98, 83, 87, 80]])