In [3]:
import numpy as np

In [6]:
type(np.array([1,2,3]))

numpy.ndarray

In [10]:
# 2d array
td = np.array([[1,2,3],[1,2,3]])
td

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
# 3d 
thrd = np.array([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])
thrd  # also called as tensors

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [15]:
# dtype array
np.array([1,2,3],dtype='float32')
np.array([1,2,3],dtype='float32').dtype

dtype('float32')

In [16]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
# arange
np.arange(1,11,2)   # this is just like the range function

array([1, 3, 5, 7, 9])

In [20]:
# reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
np.arange(1,13).reshape(2,6) 
#this only happen when u fullfill the requirement that m*n is equal to the no. of column

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#np.random 
np.ran