In [1]:
import numpy as np

In [3]:
# speed

# list
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]

c = []
import time 

start = time.time()
for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)

# numpy
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

2.649040937423706
0.13500118255615234


In [8]:
2.64/0.13
# the reson for this is 
# 1 numpy array is a static array 
# 2 in this the data is directly stored in memory not that the address is stored

20.307692307692307

In [6]:
# memory
a = [i for i in range(10000000)]
import sys

sys.getsizeof(a)

89095160

In [7]:
a = np.arange(10000000,dtype=np.int8)
sys.getsizeof(a)

10000104

In [13]:
# convenience
#numpy is better as the operations are easier

# Advance indexing

In [9]:
# Normal Indexing and slicing

a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [10]:
a[1,2]

6

In [11]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [18]:
# Fancy Indexing

a[:,[0,2,3]], a[[0,1,3]] , a[[0,3,4]]

(array([[ 0,  2,  3],
        [ 4,  6,  7],
        [ 8, 10, 11],
        [12, 14, 15],
        [16, 18, 19],
        [20, 22, 23]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [12, 13, 14, 15]]),
 array([[ 0,  1,  2,  3],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]))

In [19]:
# Boolean Indexing
a = np.random.randint(1,100,24).reshape(6,4)
a

array([[74, 82, 30, 31],
       [71, 96, 58, 35],
       [20, 57, 45, 33],
       [76, 59, 78, 94],
       [47, 50, 64, 75],
       [26, 28, 78, 67]])

In [20]:
# find all numbers greater than 50
a[a > 50]

array([74, 82, 71, 96, 58, 57, 76, 59, 78, 94, 64, 75, 78, 67])

In [21]:
# find out even numbers
a[a % 2 == 0]

array([74, 82, 30, 96, 58, 20, 76, 78, 94, 50, 64, 26, 28, 78])

In [22]:
# find all numbers greater than 50 and are even

a[(a > 50) & (a % 2 == 0)]

array([74, 82, 96, 58, 76, 78, 94, 64, 78])

In [23]:
# find all numbers not divisible by 7
a[~(a % 7 == 0)]

array([74, 82, 30, 31, 71, 96, 58, 20, 57, 45, 33, 76, 59, 78, 94, 47, 50,
       64, 75, 26, 78, 67])

<img src = "https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png">