In [1]:
import numpy as np

# np.sort
* Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([92, 84, 39,  4, 94, 51, 62, 93, 91,  5, 80, 17, 45, 30, 23])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[34, 12, 12, 14],
       [49, 55, 84, 80],
       [24, 47, 25, 22],
       [98, 19, 87, 76],
       [57, 36, 60, 66],
       [65, 83, 22, 39]])

In [4]:
np.sort(a)[::-1]

array([94, 93, 92, 91, 84, 80, 62, 51, 45, 39, 30, 23, 17,  5,  4])

In [5]:
np.sort(b,axis=0)

array([[24, 12, 12, 14],
       [34, 19, 22, 22],
       [49, 36, 25, 39],
       [57, 47, 60, 66],
       [65, 55, 84, 76],
       [98, 83, 87, 80]])

# np.append
* The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [6]:
# code
np.append(a,200)

array([ 92,  84,  39,   4,  94,  51,  62,  93,  91,   5,  80,  17,  45,
        30,  23, 200])

In [7]:
b

array([[34, 12, 12, 14],
       [49, 55, 84, 80],
       [24, 47, 25, 22],
       [98, 19, 87, 76],
       [57, 36, 60, 66],
       [65, 83, 22, 39]])

In [8]:
np.append(b,np.random.random((b.shape[0],1)),axis=1) # ye column wise he but axis rows ko match karna chahiye 

array([[34.        , 12.        , 12.        , 14.        ,  0.15291189],
       [49.        , 55.        , 84.        , 80.        ,  0.53204302],
       [24.        , 47.        , 25.        , 22.        ,  0.3529014 ],
       [98.        , 19.        , 87.        , 76.        ,  0.4338198 ],
       [57.        , 36.        , 60.        , 66.        ,  0.90372434],
       [65.        , 83.        , 22.        , 39.        ,  0.69394617]])

In [10]:
np.append(b,np.random.random((2,b.shape[1])),axis=0) 
# ye row wise addition he but axis column ko match karna chahiye

array([[3.40000000e+01, 1.20000000e+01, 1.20000000e+01, 1.40000000e+01],
       [4.90000000e+01, 5.50000000e+01, 8.40000000e+01, 8.00000000e+01],
       [2.40000000e+01, 4.70000000e+01, 2.50000000e+01, 2.20000000e+01],
       [9.80000000e+01, 1.90000000e+01, 8.70000000e+01, 7.60000000e+01],
       [5.70000000e+01, 3.60000000e+01, 6.00000000e+01, 6.60000000e+01],
       [6.50000000e+01, 8.30000000e+01, 2.20000000e+01, 3.90000000e+01],
       [6.77947867e-01, 7.87505379e-01, 9.13865497e-01, 2.30291762e-01],
       [3.46106804e-01, 5.10818406e-01, 2.72660262e-01, 5.77591231e-03]])

# np.concatenate
* numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html