In [3]:
import numpy as np

# Creation of the numpy array

In [6]:
type(np.array([1,2,3]))

numpy.ndarray

In [10]:
# 2d array
td = np.array([[1,2,3],[1,2,3]])
td

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
# 3d 
thrd = np.array([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])
thrd  # also called as tensors

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [15]:
# dtype array
np.array([1,2,3],dtype='float32')
np.array([1,2,3],dtype='float32').dtype

dtype('float32')

In [16]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
# arange
np.arange(1,11,2)   # this is just like the range function

array([1, 3, 5, 7, 9])

In [20]:
# reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
np.arange(1,13).reshape(2,6) 
#this only happen when u fullfill the requirement that m*n is equal to the no. of column

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [22]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
#np.random 
np.random.random((3,4))

array([[0.54426694, 0.2336438 , 0.12507838, 0.60587458],
       [0.84887413, 0.05878721, 0.52850044, 0.62745618],
       [0.01599406, 0.77276802, 0.69350275, 0.58784676]])

In [32]:
# np.linspace 
np.linspace(-10,10,10).reshape(2,5)
# first and the second no. tells the range and the last no. tells us the no. of no.we want

# in this the points are generated at equal distance 

array([[-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
         -1.11111111],
       [  1.11111111,   3.33333333,   5.55555556,   7.77777778,
         10.        ]])

In [33]:
# np.identity 
# to create the identity matrix of the given shape
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Attributes of numpy array

In [34]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2) # isme pehla wala 2 batata he ki kitne 2d array he baki dono 2d ka shape

In [37]:
#ndim
a3.ndim

3

In [38]:
# shape
a3.shape

(2, 2, 2)

In [39]:
#size
a3.size

8

In [44]:
#item size
a3.itemsize # tells us how much space is required by the each item of the array

4

In [47]:
#dtype
a1.dtype

dtype('int32')

# Changing the datatype of the array

In [50]:
# astype
a1.astype(np.int32)
# we use this when we are working with the large datasets

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a1.dtype

dtype('int32')

# Array operations

In [52]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [58]:
# Scalar Operations or arithmatic 
a1**2,a1*2

(array([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]], dtype=int32),
 array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]]))

In [60]:
# relational operator
a1 >= 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [62]:
# vector operation arithmatic
a1 + a2, a1**a2

(array([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]),
 array([[          0,           1,       16384,    14348907],
        [          0, -1564725563,  1159987200,   442181591],
        [          0,  1914644777, -1304428544,  -122979837]], dtype=int32))

# Array Function